export default function AboutPageHead() {
  return (
    <>
      <title>Notes - next13-movie-app</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
